server:
  port : 9191
  
spring:
 application:
  name: API-GATEWAY 
 cloud:
  gateway:
   globalcors:
    corsConfigurations:
     '[/**]':
      allowedOrigins: "*"
      allowedMethods: "*"
      allowedHeaders: "*"
   routes:
    - id: MONITOR-PLAN-SERVICE
      uri: lb://MONITOR-PLAN-SERVICE
      predicates:
       - Path=/monitorPlan/**
      filters:
       - name: CircuitBreaker
         args:
          name: MONITOR-PLAN-SERVICE
          fallbackuri: 
           forward: /monitorPlanServiceFallBack
    - id: LISTING-SERVICE
      uri: lb://LISTING-SERVICE
      predicates:
       - Path=/farmListing/**
      filters:
       - name: CircuitBreaker
         args: 
          name: LISTING-SERVICE
          fallbackuri: forward:/listingServiceFallBack
            
hystrix:
 command:
  fallbackcmd:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 4000
       
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
   client:
      serviceUrl:
         defaultZone: http://http://18.140.130.20:8761/eureka
      instance:
      preferIpAddress: true