server:
  port : 9191
  
spring:
 application:
  name: API-GATEWAY 
 cloud:
  gateway:
   globalcors:
    corsConfigurations:
     '[/**]':
      allowedOrigins: "*"
      allowedMethods: "*"
      allowedHeaders: "*"
   routes:
    - id: MONITOR-PLAN-SERVICE
      uri: lb://MONITOR-PLAN-SERVICE
      predicates:
       - Path=/monitorPlan/**
    - id: LISTING-SERVICE
      uri: lb://LISTING-SERVICE
      predicates:
       - Path=/farmListing/**
            
hystrix:
 command:
  fallbackcmd:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 4000
       
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
   client:
      serviceUrl:
         defaultZone: http://18.141.137.69:8761/eureka
      instance:
      preferIpAddress: true